use mock::build_mocking_text;

const NORMAL_CASES: &[(&str, &str)] = &[
    ("", ""),
    ("a", "a"),
    ("e", "e"),
    ("i", "i"),
    ("l", "l"),
    ("o", "o"),
    ("x", "x"),
    ("xy", "xY"),
    ("xyz", "xYz"),
    ("xyzw", "xYzW"),
    ("hello", "HeLlo"),
    ("HELLO", "HeLlo"),
    ("HeLLo", "HeLlo"),
    ("test", "TeSt"),
    ("foobar", "FooBaR"),
    ("foo bar", "Foo bAr"),
    ("hello world", "HeLlo WoRlD"),
    ("abcdefghijklmnopqrstuvwxyz", "aBcDeFgHiJKlMNoPqRsTuVwXyZ"),
    ("mark", "mArK"),
    ("rob", "RoB"),
    ("marketing", "mArKeTiNg"),
    ("probleem", "pRobLEeM"),
    ("hallo wereld", "haLLo WeReld"),
    ("aeiou", "AeIoU"),
    ("AEIOU", "AeIoU"),
    ("eeeee", "eEeEe"),
    ("iiiii", "iIiIi"),
    ("lllll", "lLlLl"),
    ("ooooo", "oOoOo"),
    ("eilo", "eIlo"),
    ("oil", "oIl"),
    ("lie", "lIe"),
    ("EiLo", "eIlo"),
    ("LoLi", "lOli"),
    ("OiLe", "oIle"),
    ("eieieieieieil", "eIeIeIeIeIeIl"),
    ("lolololol", "lOlOlOlOl"),
    ("EEEEE", "eEeEe"),
    ("OOOOO", "oOoOo"),
    ("LLLLL", "lLlLl"),
    ("IIIII", "iIiIi"),
    ("123", "123"),
    ("abc123", "aBc123"),
    ("hello!", "HeLlo!"),
    ("hello?", "HeLlo?"),
    ("hello.", "HeLlo."),
    ("hello, world!", "HeLlo, WoRlD!"),
    ("it's", "iT'S"),
    ("\"hello\"", "\"HelLo\""),
    ("a&b", "a&b"),
    ("foo@bar", "Foo@bAr"),
    ("100%", "100%"),
    ("#hashtag", "#HaShTaG"),
    ("C++", "C++"),
    ("hello-world", "HeLlo-WoRlD"),
    ("hello_world", "HeLlo_WoRlD"),
    ("hello/world", "HeLlo/WoRlD"),
    ("hello\\world", "HeLlo\\WoRlD"),
    ("a b c d e", "a b c d e"),
    (" ", " "),
    ("  ", "  "),
    ("   leading", "   leADiNG"),
    ("trailing   ", "TrAiLiNg   "),
    ("hello  world", "HeLlo  WoRlD"),
    ("multiple   spaces   here", "MUlTiPle   sPaCeS   HeRe"),
    ("hello\tworld", "HeLlo\tWoRlD"),
    ("caf\u{e9}", "cAf\u{c9}"),
    ("na\u{ef}ve", "nA\u{ef}Ve"),
    ("\u{fc}ber", "\u{fc}BeR"),
    ("r\u{e9}sum\u{e9}", "r\u{c9}sUm\u{c9}"),
    ("\u{1f525}", "\u{1f525}"),
    ("\u{65e5}\u{672c}\u{8a9e}", "\u{65e5}\u{672c}\u{8a9e}"),
    ("\u{f1}", "\u{f1}"),
    ("\u{df}", "\u{df}"),
    ("aa", "aA"),
    ("van", "vAn"),
    ("je", "Je"),
    ("ik", "iK"),
    ("is", "iS"),
    ("ja", "jA"),
    ("nu", "nU"),
    ("nou", "NoU"),
    ("op", "oP"),
    ("om", "oM"),
    ("de", "De"),
    ("el", "el"),
    ("in", "iN"),
    ("tje", "tJe"),
    ("ver", "VeR"),
    ("aardvark", "aArDvArK"),
    ("aardappel", "AaRdApPel"),
    ("eigenlijk", "eiGeNliJk"),
    ("verjaardagsfeestje", "VeRjAaRdAgSFeeStJe"),
    ("verovering", "VeRoVeRiNg"),
];

const GARBLE_CASES: &[(&str, &str)] = &[
    ("", ""),
    ("a", "a"),
    ("e", "e"),
    ("i", "i"),
    ("l", "l"),
    ("o", "o"),
    ("foobar", "FooHwBaR"),
    ("foo bar", "FooHw bAr"),
    ("hello", "HeehLLo"),
    ("HELLO", "HeehLLo"),
    ("hello world", "HeehLLo WoRlD"),
    ("test", "TeSt"),
    ("mark", "mArK"),
    ("rob", "RooWb"),
    ("marketing", "MaRKeTDiHnGh"),
    ("probleem", "PRooWBlEeHM"),
    ("hallo wereld", "haLLo WeReeHlD"),
    ("eeeee", "eeHeeHe"),
    ("iiiii", "iIiIi"),
    ("lllll", "lLlLl"),
    ("ooooo", "oohWoohWo"),
    ("eilo", "eiHlo"),
    ("oil", "oiHl"),
    ("lie", "lIeH"),
    ("EiLo", "eiHlo"),
    ("LoLi", "lOli"),
    ("OiLe", "oiHle"),
    ("eieieieieieil", "eiHeiHeiHeiHeiHeiHl"),
    ("lolololol", "lOlOlOlOl"),
    ("aeiou", "AeiHoUw"),
    ("AEIOU", "AeiHoUw"),
    ("aa", "aAh"),
    ("aat", "aAhTd"),
    ("ch", "gCh"),
    ("dt", "dTdTtD"),
    ("ee", "eeh"),
    ("ie", "ieh"),
    ("oo", "oohW"),
    ("kk", "cKk"),
    ("van", "fAhN"),
    ("je", "JeH"),
    ("ik", "iCcK"),
    ("is", "iShJ"),
    ("ja", "jAaH"),
    ("nu", "nUuH"),
    ("nou", "NoUwH"),
    ("op", "oHp"),
    ("om", "oHmM"),
    ("de", "DeH"),
    ("el", "eeHl"),
    ("in", "iHhN"),
    ("tje", "tJuH"),
    ("ver", "FeHr"),
    ("cheese", "GcHeehSe"),
    ("aardvark", "aAhRdVaRk"),
    ("programmeren", "pRoowGrAmMeHReHN"),
    ("verjaardagsfeestje", "FeHrJaAhAhRdTaGsFeehStJuH"),
    ("ijsje", "iJhSJeH"),
    ("grootte", "gRooWoTTe"),
    ("aandeelhouder", "aAhNDeHeehLHoUwDeHr"),
    ("verovering", "FeHRooWfVeRiHnGh"),
    ("eigenlijk", "eihGeHNliJcK"),
    ("vandaag", "fAhNdAaHg"),
    ("verkopen", "FeHrKoHPeHN"),
    ("overloop", "oowFVeRlOoHWp"),
    ("verjaardag", "FeHrJaAhAhRdTaG"),
    ("voorbij", "FooHrBiJh"),
    ("verschijnen", "FeHRsGcHiJhNeHn"),
    ("vermarkting", "FeHrMaRkTiHnGh"),
    ("aardappel", "aAhRdApPeeHl"),
    ("rob is de mark", "RooWb iShJ DeH mArK"),
    ("de kat op de mat", "DeH kAt oHp DeH mAt"),
    ("ik ben je moeder", "iCcK BeHn JeH MoehDeHr"),
    ("van de aardappel", "fAhN DeH aAhRdApPeeHl"),
    ("oo ee aa ii", "oohW eeh aAh ii"),
    ("a b c d e", "a b c d e"),
    ("123", "123"),
    ("abc123", "aBc123"),
    ("hello!", "HeehLLo!"),
    ("hello, world!", "HeehLLo, WoRlD!"),
    ("it's", "iHt's"),
    ("foo@bar", "FooHw@bAr"),
    ("#hashtag", "#HaHsZhTaG"),
    ("C++", "C++"),
    ("100%", "100%"),
    ("caf\u{e9}", "cAf\u{c9}"),
    ("na\u{ef}ve", "nA\u{ef}Ve"),
    ("\u{fc}ber", "\u{fc}BeR"),
    ("\u{1f525}", "\u{1f525}"),
    ("\u{65e5}\u{672c}\u{8a9e}", "\u{65e5}\u{672c}\u{8a9e}"),
    ("xyz", "xYzS"),
    ("xyzw", "xYzSw"),
    ("xyzwv", "xYzSwV"),
    ("hello-world", "HeehLLo-WoRlD"),
    ("hello_world", "HeehLLo_WoRlD"),
    ("   leading", "   leADiHNgH"),
    ("trailing   ", "tRAiHliHnGh   "),
    ("hello  world", "HeehLLo  WoRlD"),
    ("multiple   spaces   here", "MUlTiPle   sPaCeS   HeRe"),
];

#[test]
fn test_normal_parity() {
    for (input, expected) in NORMAL_CASES {
        assert_eq!(
            &build_mocking_text(input, false),
            expected,
            "normal mode failed for input: {:?}",
            input
        );
    }
}

#[test]
fn test_garble_parity() {
    for (input, expected) in GARBLE_CASES {
        assert_eq!(
            &build_mocking_text(input, true),
            expected,
            "garble mode failed for input: {:?}",
            input
        );
    }
}
